language: node_js

node_js:
  - "10.24.1"

install:
  - yarn install

script:
  - npm run coverall

# Send coverage data to Coveralls
after_script: "cat coverage/ngx-i18nsupport/lcov.info >coverage/ngx-i18nsupport.lcov\
 && cat coverage/tooling/lcov.info >coverage/tooling.lcov\
 && cat coverage/ngx-i18nsupport-lib/lcov.info >coverage/ngx-i18nsupport-lib.lcov\
 && node_modules/.bin/lcov-result-merger coverage/*.lcov | node_modules/.bin/coveralls"
